name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          **/yarn.lock
          **/.production
        key: node_modules-${{ hashFiles('**/package.json') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
