name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Typechecking
        run: yarn typecheck

      - name: Run the tests
        run: yarn test:ci

      - name: Run build
        run: yarn build
