name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/yarn.lock
            **/.production
          key: node_modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Run Typechecking
        run: yarn typecheck

      - name: Run the tests
        run: yarn test:ci

      - name: Run build
        run: yarn build
